### ISSUE TITLE
Oilrig

### ISSUE THREAD

**Issue by inikishev** [frack113/sigma_redcanaryco#1]
hello i installed https://obsidian.md/ and it says oilrig https://www.virustotal.com/gui/file/bdceb2f2cb606ce98a8e3de5b42f2f5ea197c8a50fb34db42ea2fc00f5a385d8/behavior

**Comment by frack113** [comment]
Hello,
Sorry but I am not affiliated with virustotal or SOC Prime Threat Detection Marketplace.
The rule match because "nsExec.dll" is written.
You need to ask SOC Prime.

**Comment by frack113** [comment]
Not related to the project
