### ISSUE TITLE
Too broad of rules causes many alerts on Advanced BAT to EXE Converter compiled batch files. 20 years in development

### ISSUE THREAD

**Issue by BrandonDargo** [frack113/sigma_redcanaryco#2]
Hello,

Please fix your very broad rules that affect my product and thousands of users. There are millions of EXE generated by my product "Advanced BAT to EXE Converter" your repository comes up multiple times from recent changes you made:

https://www.virustotal.com/gui/file/eb4c6bb9f8df78c4161ffbdeca8032fb5e07a7c71fb765dbe63f77ddc3a9c56c?nocache=1

These alerts come up on every batch file compiled to EXE with my product. I have been doing this for 20 years and I have enough of a headache with antivirus companies before this recent change by you. All development software has false positives but you cannot simply make a very broad rule like this and not see thousands of false positives from hundreds of developers:

"Matches rule CMD Shell Output Redirect by frack113 at Sigma Integrated Rule Set (GitHub)
Detects the use of the redirection character ">" to redicrect information in commandline"

**Comment by frack113** [comment]
Hello,
Sorry but I am not affiliated with virustotal.

The rule is low :
[low: Notable event but rarely an incident. Low rated events can be relevant in high numbers or combination with others. Immediate reaction shouldn't be necessary, but a regular review is recommended.](https://github.com/SigmaHQ/sigma-specification/blob/main/Sigma_specification.md#level)

The rule has been public since 22 January 2022. (18 months)
You can use github to check.

Just because you don't like an artist's painting doesn't mean you should take it out on the paint manufacturer.

**Comment by BrandonDargo** [comment]
There are over 1 million EXE made by my product in the wild. Government agencies and universities use my product. Every one scanning the EXE made by my product results in your username and rule showing up on VirusTotal. This is undesirable. I already spend enough time dealing with false positives as does anyone that is in the development software category. It would be greatly appreciated if you can fix this.

There are multiple "rules" you have made that affect my product. Not just the one I posted above with the misspelling.

https://imgur.com/a/GJGrXdh

**Comment by BrandonDargo** [comment]
I don't use powershell so your rules are too broad man. I really need you to fix this. When detecting malware, the whole point is to not cause a million false positives. 5 sigma rules all from you only.

**Comment by BrandonDargo** [comment]
You speak of an artist's painting but this looks like a vandal with a rattle can . A real artist wouldn't make such mistakes. You have an anonymous account and seem to have targeted my product that I have spent 2 decades on.

**Comment by frack113** [comment]
Not related to the project
